CFLAGS= -Wall -fpic -coverage -lm -std=c99

rngs.o: rngs.h rngs.c
	gcc -c rngs.c -g  $(CFLAGS)

dominion.o: dominion.h dominion.c rngs.o
	gcc -c dominion.c -g  $(CFLAGS)

playdom: dominion.o playdom.c
	gcc -o playdom playdom.c -g dominion.o rngs.o $(CFLAGS)
#To run playdom you need to entere: ./playdom <any integer number> like ./playdom 10*/

testDrawCard: testDrawCard.c dominion.o rngs.o
	gcc  -o testDrawCard -g  testDrawCard.c dominion.o rngs.o $(CFLAGS)

interface.o: interface.h interface.c
	gcc -c interface.c -g  $(CFLAGS)

runtests: testDrawCard 
	./testDrawCard &> unittestresult.out
	gcov dominion.c >> unittestresult.out
	cat dominion.c.gcov >> unittestresult.out

player: player.c interface.o
	gcc -o player player.c -g  dominion.o rngs.o interface.o $(CFLAGS)

all: playdom player 

clean:
	rm -f *.o playdom.exe playdom player player.exe  *.gcov *.gcda *.gcno *.so *.out testDrawCard testDrawCard.exe randomtestcard1 randomtestcard2 randomtestcard3

rand1: randomtestcard1.c dominion.o rngs.o 
	gcc  -o randomtestcard1 -g randomtestcard1.c dominion.o rngs.o $(CFLAGS)

rand2: randomtestcard2.c dominion.o rngs.o 
	gcc  -o randomtestcard2 -g randomtestcard2.c dominion.o rngs.o $(CFLAGS)

rand3: randomtestcard3.c dominion.o rngs.o 
	gcc  -o randomtestcard3 -g randomtestcard3.c dominion.o rngs.o $(CFLAGS)

randomtestresults: rand1 rand2 rand3
	./randomtestcard1	>> randomtestcardresults.out
	gcov -b -f randomtestcard1 >> randomtestcardresults.out
	echo "" >> randomtestcardresults.out
	./randomtestcard2	>> randomtestcardresults.out
	gcov -b -f randomtestcard2 >> randomtestcardresults.out
	echo "" >> randomtestcardresults.out
	./randomtestcard3	>> randomtestcardresults.out
	gcov -b -f randomtestcard3 >> randomtestcardresults.out
	echo "" >> randomtestcardresults.out

